config/routes.rb
Rails.application.routes.draw do

  root :to => "wiki_informations#index"

  get "search" => "search#index", :as => 'search'

  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy", :as => "logout"
  get "logout" => "sessions#destroy" # ログインできなくなる対策で
  get "oauth/callback" => "sessions#callback"
  get "oauth/:provider" => "sessions#oauth", :as => :auth_at_provider
  resources :password_resets, only: %i[new create edit update]

  get "/setting" => "users#setting", :as => 'user_setting'
  put "/setting/:id" => "users#update", :as => 'update_setting'
  get "/users/:token/activate" => "users#activate", :as => 'activate_user'
  put "/users/:token/register" => "users#register", :as => 'regist_user'

  namespace :admin do
    resources :users do
      member do
        get :candidates_wiki
        post :add_visibility_wiki
        delete :delete_visibility_wiki
        get :resend_invite_mail
        patch :unlock
      end
    end
  end
  post "/admin/users/invite" => 'admin/users#invite_user', :as => 'invite_user'

  resources :wiki_infos, :controller => 'wiki_informations', :only => [:index, :new, :create]
  get ':wiki_name/candidates_users' => 'wiki_informations#visible_wiki_candidates_users', :as => :candidates_users
  get ':wiki_name' => 'wiki_informations#show', :as => 'wiki'
  get ':wiki_name/edit' => 'wiki_informations#edit', :as => 'edit_wiki_info'
  put ':wiki_name' => 'wiki_informations#update', :as => 'update_wiki'
  post ':wiki_name/add_authority_user' => 'wiki_informations#add_authority_user', :as => 'add_authority_user'
  delete '/:wiki_name/remove_authority_user' => 'wiki_informations#remove_authority_user', :as => 'remove_authority_user'
  delete '/:wiki_name' => 'wiki_informations#destroy', :as => 'wiki_info'

  scope ':wiki_name' do
    resources :pages, only: [:index, :create, :new]
    get '/list_view_index' => 'pages#list_view_index', :as => 'list_view_pages'
    get '/globe_view_index' => 'pages#globe_view_index', :as => 'globe_view_pages'
    get '/markdown_help' => 'pages#help', :as => 'help'
    post '/preview' => 'pages#preview', :as => 'preview_page'
    get '/:page_name/histories' => 'pages#histories', :as => 'histories_page'
    put '/:page_name/histories/revert_page' => 'pages#revert', :as => 'revert_page'
    get '/:page_name' => 'pages#show', :as => 'page'
    get '/:page_name/edit' => 'pages#edit', :as => 'edit_page'
    put '/:page_name' => 'pages#update', :as => 'update_page'
    post '/:page_name/attachments' => 'pages#file_upload', :as => 'file_upload'
    get '/:page_name/attachments/:id' => 'pages#attachment', :as => 'attachment'
    delete '/:page_name/attachments/:id' => 'pages#file_destroy', :as => 'attachments'
    delete '/:page_name' => 'pages#destroy', :as => 'delete_page'
  end
end

app/views/pages/_form.html.haml
- newly = @page.new_record?
- form_url = newly ? pages_path(wiki_name: @wiki_info.name) : page_path(wiki_name: @wiki_info.name, page_name: @page.url_name)
- http_method = newly ? :post : :put
- canceled_to_url = newly ? wiki_info_path(wiki_name: @wiki_info.name) : page_path(wiki_name: @wiki_info.name, page_name: @page.url_name)

= error_messages_for(@page)

.col-md-6
  = form_for(@page, url: form_url, html: {method: http_method, id: 'wiki-page-form', role: 'form'}) do |f|
    #page-content
      .field
        = f.hidden_field :url_name
        = f.hidden_field :name
      .form-group
        = f.text_area :body, class: 'form-control', id: 'markdown-text', rows: 10
      .col-md-offset-2
        = f.submit (newly ? t('actions.regist') : t('actions.update')), class: 'btn btn-primary', id: 'page-submit-btn'
        = link_to t('actions.cancel'), canceled_to_url, class: 'btn'
        = link_to fa_icon('question-circle 2x'), help_path, class: 'btn', target: 'blank', rel: 'tooltip', :"data-placement" => 'top', title: t('terms.markdown_help')
        = link_to 'http://www.emoji-cheat-sheet.com/', target: 'blank', rel: 'tooltip', :"data-placement" => 'top', title: t('terms.can_use_emoji') do
          = emoji_tag 'question'
          = emoji_tag Emoji.names.sample

.col-md-6
  .well.well-small#preview-result

:coffeescript
  $ ->
    $('#markdown-text').autosize({append: "\n"})

:css
  #markdown-text {
    vertical-align: top;
    transition: height 0.2s;
    -webkit-transition: height 0.2s;
    -moz-transition: height 0.2s;
   }

app/views/pages/_globe_view_index.html.haml
%h3
  = link_to fa_icon('list-ul'), list_view_pages_path(wiki_name: @wiki_info.name), remote: true, class: 'switch-view'
  = t('terms.index_page')
  = link_to fa_icon('repeat'), globe_view_pages_path(wiki_name: @wiki_info.name), remote: true, class: 'reload-page-list'

#tag-cloud
  - @pages.each do |page|
    = link_to page.name, page_path(wiki_name: @wiki_info.name, page_name: page.url_name), class: 'btn btn-default btn-xs'

:coffee
  radius = 200
  dtr = Math.PI / 180
  d = 400

  mcList = []
  active = false
  lasta = lastb = 1
  distr = true
  tspeed = 4
  size = 300

  mouseX = mouseY = 0

  howElliptical = 1

  aA = null
  oDiv = null

  update = ->
    if active
      a = (-Math.min( Math.max( -mouseY, -size ), size ) / radius ) * tspeed
      b = (Math.min( Math.max( -mouseX, -size ), size ) / radius ) * tspeed
    else
      a = lasta * 0.98
      b = lastb * 0.98
    lasta = a
    lastb = b

    if Math.abs(a) <= 0.01 and Math.abs(b) <= 0.01
      return @

    c = 0
    sineCosine(a, b, c)
    for mc in mcList
      rx1 = mc.cx
      ry1 = mc.cy * window.ca + mc.cz * (-window.sa)
      rz1 = mc.cy * window.sa + mc.cz * window.ca

      rx2 = rx1 * window.cb + rz1 * window.sb
      ry2 = ry1
      rz2 = rx1 * (-window.sb) + rz1 * window.cb

      rx3 = rx2 * window.cc + ry2 * (-window.sc)
      ry3 = rx2 * window.sc + ry2 * window.cc
      rz3 = rz2

      mc.cx = rx3
      mc.cy = ry3
      mc.cz = rz3

      per = d / (d + rz3)

      mc.x = (howElliptical * rx3 * per) - (howElliptical * 2)
      mc.y = ry3 * per
      mc.scale = per
      $(mc).css 'alpha', per
      $(mc).css 'alpha', (mc.alpha - 0.6) * (10 / 6)

    doPosition()
    depthSort()

  depthSort = ->
    aTmp = []
    for tmp in aA
      aTmp.push tmp

    aTmp.sort (vItem1, vItem2) ->
      if vItem1.cz > vItem2.cz
        return -1
      else if vItem1.cz < vItem2.cz
        return 1
      else
        return 0

    for i in [0..aTmp.length]
      $(aTmp[i]).css 'z-index', i

  positionAll = ->
    phi = 0
    theta = 0
    max = mcList.length

    aTmp = []

    # ランダムの順位を付ける
    for aAtmp in aA
      aTmp.push aAtmp

    aTmp.sort ->
      if Math.random() < 0.5 then 1 else -1

    for tmp in aTmp
      oDiv.append tmp

    i = 1
    for mc in mcList
      if distr
        phi = Math.acos(-1+(2*i-1)/max)
        theta = Math.sqrt(max * Math.PI) * phi
      else
        phi = Math.random() * Math.PI
        theta = Math.random() * (2 * Math.PI)

      # 経緯度の変換
      mc.cx = radius * Math.cos(theta) * Math.sin(phi)
      mc.cy = radius * Math.sin(theta) * Math.sin(phi)
      mc.cz = radius * Math.cos(phi)
      $(aA[i-1]).css
        'left': Math.abs(mc.cx + oDiv.width()/2 - mc.offsetWidth/2)
        'top': Math.abs(mc.cy + oDiv.height()/2 - mc.offsetHeight/2)
      i += 1

  doPosition = ->
    l = oDiv.width() / 2
    t = oDiv.height() / 2
    i = 0
    for mc in mcList
      $(aA[i]).css
        'left': Math.abs(mc.cx + l - mc.offsetWidth / 2)
        'top': Math.abs(mc.cy + t - mc.offsetHeight / 2)
        'font-size': Math.ceil(12 * mc.scale / 2) + 8 + 'px'
        'filter': "alpha(opacity=" + 100 * mc.alpha + ")"
        'opacity': mc.alpha
      i += 1

  sineCosine = (a, b, c) ->
    window.sa = Math.sin(a * dtr)
    window.ca = Math.cos(a * dtr)
    window.sb = Math.sin(b * dtr)
    window.cb = Math.cos(b * dtr)
    window.sc = Math.sin(c * dtr)
    window.cc = Math.cos(c * dtr)

  $ ->
    oDiv = $('#tag-cloud')
    aA = oDiv.find('a')

    for cloudTag in aA
      oTag =
        offsetWidth: cloudTag.offsetWidth
        offsetHeight: cloudTag.offsetHeight
      mcList.push oTag

    sineCosine(0, 0, 0)
    positionAll()

    oDiv.mouseover ->
      active = false

    oDiv.mouseout ->
      active = true

    oDiv.on 'mousemove', (ev) ->
      oEvent = window.event || ev
      mouseX = oEvent.clientX - (oDiv.offset().left + oDiv.width()/2)
      mouseY = oEvent.clientY - (oDiv.offset().top + oDiv.height()/2)
      mouseX /= 5
      mouseY /= 5

    setInterval(update, 30)

app/views/pages/_list_view_index.html.haml
%h3
  = link_to fa_icon('globe'), globe_view_pages_path(wiki_name: @wiki_info.name), remote: true, class: 'switch-view'
  = t('terms.index_page')
  = link_to fa_icon('repeat'), list_view_pages_path(wiki_name: @wiki_info.name), remote: true, class: 'reload-page-list'

- @pages.each do |page|
  = link_to page.name, page_path(wiki_name: @wiki_info.name, page_name: page.url_name), class: 'btn btn-default btn-md'

app/views/pages/_menu_link.html.haml
.navbar-text= link_to t('terms.index_page'), wiki_info_path(wiki_name: @wiki_info.name)
.navbar-text= link_to t('terms.new_page'), new_page_path(wiki_name: @wiki_info.name)

app/views/pages/edit.html.haml
= content_for :menu_link do
  = render 'menu_link'

= content_for :page_editable do
  .row
    %h4.text-center
      %small URL:
      = "/#{@wiki_info.name}/"
      = text_field_tag :page, @page.url_name, placeholder: t('terms.page_name_format_placeholder'), id: 'edit-page-url-name', required: true

    %h3.text-center
      %small Page name:
      = text_field_tag :page, @page.name, placeholder: t('terms.page_name_format_placeholder'), id: 'edit-page-name', required: true

    .rows
      .col-md-offset-2
        #editing-user.label.label-warning.hide
    = render 'form'

    = subscribe_to "/pages/#{@page.id}"

  :coffeescript
    $ ->
      edited_text = false
      $(window).on 'beforeunload', (event) ->
        return "#{t('terms.confirm_unload_page')}" if edited_form
      $('#page-submit-btn').click ->
        $(window).off 'beforeunload'

      $('#edit-page-name').keyup ->
        $('#page_name').val( $('#edit-page-name').val())
      $('#edit-page-url-name').keyup ->
        $('#page_url_name').val( $('#edit-page-url-name').val())

      render_preview = ->
        url = "#{preview_page_url(wiki_name: @wiki_info.name, page_name: @page.url_name)}"
        sending_page_body(url, get_markdown_text)

      get_markdown_text = ->
        $('#markdown-text').val()

      sending_page_body = (request_url, body) ->
        $.ajax
          type: 'POST'
          url: request_url
          data:
            previewed: true
            edited_user_id: "#{current_user.id}"
            body: body
          success: (data, textStatus, jqXHR) ->
            console.log data
            $('#preview-result').html data
          error: (data, textStatus, jqXHR) ->
            console.log textStatus

      prev = initial = get_markdown_text()
      $('#markdown-text').keyup ->
        $('#page-submit-btn').removeAttr("disabled").addClass("btn-primary")
        $('#editing-user').addClass('hide')
        markdown_text = get_markdown_text()
        unless prev == markdown_text
          prev = markdown_text
          render_preview()
          edited_text = true

      PrivatePub.subscribe "/pages/#{@page.id}", (data, channel) ->
        unless data.edited_user_id == "#{current_user.id}"
          $('#markdown-text').animate({borderColor: '#fbf300' }, 'slow')
          $('#markdown-text').val data.body
          $('#preview-result').html data.parsed_body
          $('#editing-user').html(data.editing_word)
          $('#editing-user').removeClass('hide')
          $('#page-submit-btn').attr("disabled", "true").removeClass("btn-primary")
          $('#markdown-text').animate({borderColor: '#fff' }, 'slow')

      # parse on firstview
      render_preview()

app/views/pages/help.html.haml
%h1
  記法
  %a.anchor{href: "#記法", id: "記法"}
%p
  Markdownと言われる記法です
  (
  %a{href: "http://daringfireball.net/projects/markdown/syntax.php)%E3%82%92%E3%81%94%E8%A6%A7%E4%B8%8B%E3%81%95%E3%81%84%E3%80%82"} http://daringfireball.net/projects/markdown/syntax.php)をご覧下さい。
  また、コードに関する記法は
  %a{href: "http://github.github.com/github-flavored-markdown/"}> GitHub Flavored Markdown
  に準拠しています。
%h2
  Format Text - テキストの装飾
  %a.anchor{href: "#Format-Text---テキストの装飾", id: "Format-Text---テキストの装飾"}
%h3
  Headers - 見出し
  %a.anchor{href: "#Headers---見出し", id: "Headers---見出し"}
%ul
  %li # これはH1タグです
  %li ## これはH2タグです
  %li ###### 見出しは６段階まで表現できます
%h3
  Emphasis - 強調
  %a.anchor{href: "#Emphasis---強調", id: "Emphasis---強調"}
%ul
  %li
    イタリック
    %ul
      %li *これはイタリック体です*
      %li _これもイタリック体です_
      %li
        %em> これは
        イタリック体になりません  (前後に空白を入れてください。)
  %li
    太字
    %ul
      %li **これは太字です**
      %li __これも太字です__
%h2
  Lists - リスト
  %a.anchor{href: "#Lists---リスト", id: "Lists---リスト"}
%h3
  順序なしリスト
  %a.anchor{href: "#順序なしリスト", id: "順序なしリスト"}
%ul
  %li 文頭に「*」「+」「-」のいずれかを入れると順序なしリストになります
  %li 要点をまとめる際に便利です
  %li
    リストを挿入する際は、
    %strong リストの上下に空行がないと正しく表示されません
%h3
  順序つきリスト
  %a.anchor{href: "#順序つきリスト", id: "順序つきリスト"}
%ol
  %li 文頭に「数字.」を入れると順序つきリストになります
  %li 1.2.3.と入れていくといい具合です
  %li
    リストを挿入する際は、
    %strong リストの上下に空行がないと正しく表示されません
%h2
  Tables - テーブル
  %a.anchor{href: "#Tables---テーブル", id: "Tables---テーブル"}
%blockquote
  %p | 左揃え      |   中央揃え    |       右揃え |
  %p |:-----------|:------------:|------------:|
  %p | This       |     This     |        This |
  %p | column     |    column    |      column |
  %p | will       |     will     |        will |
  %p | be         |      be      |          be |
  %p | left       |    center    |       right |
  %p | aligned    |   aligned    |     aligned |
%p 上記のように書くと、以下のように表示されます。
%table
  %thead
    %tr
      %th{align: "left"} Left align
      %th{align: "right"} Right align
      %th{align: "center"} Center align
  %tbody
    %tr
      %td{align: "left"} This
      %td{align: "right"} This
      %td{align: "center"} This
    %tr
      %td{align: "left"} column
      %td{align: "right"} column
      %td{align: "center"} column
    %tr
      %td{align: "left"} will
      %td{align: "right"} will
      %td{align: "center"} will
    %tr
      %td{align: "left"} be
      %td{align: "right"} be
      %td{align: "center"} be
    %tr
      %td{align: "left"} left
      %td{align: "right"} right
      %td{align: "center"} center
    %tr
      %td{align: "left"} aligned
      %td{align: "right"} aligned
      %td{align: "center"} aligned
%h2
  Blockquotes - 引用
  %a.anchor{href: "#Blockquotes---引用", id: "Blockquotes---引用"}
%blockquote
  %p
    \> 文頭に>を置くことで引用になります。
    \> 複数行にまたがる場合、改行のたびにこの記号を置く必要があります。
    \>
    %strong 引用の上下にはリストと同じく空行がないと正しく表示されません
    \> 引用の中に別のMarkdownを使用することも可能です。
  %blockquote
    %p これはネストされた引用です。
%h2
  Horizontal rules - 水平線
  %a.anchor{href: "#Horizontal-rules---水平線", id: "Horizontal-rules---水平線"}
%p 下記は全て水平線として表示されます
%blockquote
  %p * * *
  %p ***
  %p *****
  %p - - -
  %p ---------------------------------------
%h2
  Links - リンク
  %a.anchor{href: "#Links---リンク", id: "Links---リンク"}
%ul
  %li
    [リンクテキスト](URL "タイトル")
    %ul
      %li タイトル付きのリンクを投稿できます。
%p
  %strong 例
%blockquote
  %p
    [Leafy](
    %a{href: "http://www.leafy.in"} http://www.leafy.in
    "マウスをおいた時に表示する文字")
%p
  %a{href: "http://www.leafy.in", title: "マウスをおいた時に表示する文字"} Leafy
%ul
  %li
    [リンクテキスト](URL)
    %ul
      %li こちらはタイトル無しのリンクになります。
%p
  %strong 例
%blockquote
  %p
    [Homepage](
    %a{href: "http://everyleaf.com"}> http://everyleaf.com
    )
%p
  %a{href: "http://everyleaf.com"} Homepage
%h2
  Images - 画像埋め込み
  %a.anchor{href: "#Images---画像埋め込み", id: "Images---画像埋め込み"}
%ul
  %li
    \![代替テキスト](画像のURL)
    %ul
      %li タイトル無しの画像を埋め込む
  %li
    \![代替テキスト](画像のURL "画像タイトル")
    %ul
      %li タイトル有りの画像を埋め込む
%p
  %strong 例
%blockquote
  %p
    \![会社ロゴ](
    %a{href: "http://everyleaf.com/images/logo.jpg"} http://everyleaf.com/images/logo.jpg
    "logo")
%p
  %img{alt: "会社ロゴ", src: "http://everyleaf.com/images/logo.jpg", title: "logo"}/
%h2
  Code - コードの挿入
  %a.anchor{href: "#Code---コードの挿入", id: "Code---コードの挿入"}
%p たとえば、Rubyで記述したコードを表示します。
%p
  %strong コードブロック上下に空行を挿入しないと正しく表示されないことがあります。
%blockquote
  %p ``ruby
  %p # コメント
  %p def hoge(name)
  %p return "No name" unless name
  %p puts "hello \#{name}"
  %p end
  %p ```
%p また、コードをインライン表示することも可能です。
%blockquote
  %p ` puts 'hoge'` はプログラマのための知識記録アプリです。
%p
  %strong 結果
%p
  %code puts 'hoge'
  はプログラマのための知識記録アプリです。
%h2
  その他
  %a.anchor{href: "#その他", id: "その他"}
%p バックスラッシュ[\]をMarkdownの前に挿入することで、Markdownをエスケープ(無効化)することができます。
%p
  %strong 例
%blockquote
  %p
    \# H1
    エスケープされています

app/views/pages/histories.html.haml
= content_for :menu_link do
  = render 'menu_link'

- content_for :right_area do
  %table.table.table-hover
    - @page.histories(true).each do |history|
      %tr{"data-href" => (histories_page_path(wiki_name: @wiki_info.name, page_name: @page.url_name, sha: history[:sha]))}
        %td= history[:date].to_s(:db)
        %td= history[:author]

%h2
  = truncate(@wiki_info.name, length: 20)
  &raquo;
  = link_to @page.url_name, page_path(wiki_name: @wiki_info.name, page_name: @page.url_name)
  = t('terms.history_of')

- if @former_page.present?

  %h4
    = @page.date(params[:sha]).to_s(:db)
    = "(by #{@page.author_name(params[:sha])})"

  %hr

  -# 一旦 revert 機能を閉じる(gollum-libのrevert がうまく動かない)
  -#   = form_for @page, as: :page, url: revert_page_path(wiki_name: @wiki_info.name, page_name: @page.url_name, sha: params[:sha]), method: :put do |f|
  -#     = f.submit t('actions.revert_page'), class: 'btn btn-warning', confirm: t('actions.confirm_revert')

  #page-raw-content.hide
    = @former_page
  #page-content
    .markdown-body

  %hr
  %h4 Diff
  = simple_format h(@page.diff(params[:sha]))
  %hr

  :coffee
    $ ->
      $('tbody tr[data-href]').delegate '*', 'click', ->
        window.location = $(this).parents('tr').data('href')
      request_url = "#{preview_page_url(wiki_name: @wiki_info.name, page_name: @page.url_name, sha: params[:sha])}"
      PageContent.replace(request_url, $('#page-raw-content').html(), '#page-content')

app/views/pages/index.html.haml
= content_for :menu_link do
  = render 'pages/menu_link'

= render 'shared/flash_messages'

.row
  .col-md-2
    %h4
      .label{class: ("label-#{@wiki_info.private_policy_label}")}= @wiki_info.private_policy
    - if @wiki_info.is_private? && @wiki_info.controllable_by?(current_user)
      = link_to "#private_members", id: 'private_members_modal', data: {toggle: "modal"} do
        %h5
          = fa_icon('users')
          member
  .col-md-8
    %h1.text-center
      - if @wiki_info.private?
        %small= fa_icon('lock')
      = truncate(@wiki_info.name, length: 20)
  .col-md-2
    - unless current_user.limited?
      .pull-right
        = link_to fa_icon('edit 2x'), edit_wiki_info_path(wiki_name: @wiki_info.name), class: 'action-icons'
        = link_to fa_icon('trash-o 2x'), wiki_info_path(wiki_name: @wiki_info.name), class: 'action-icons', data: {method: :delete, confirm: t('actions.confirm_delete')}

:coffee
  $('.action-icons').hover (e) ->
    $(e.target).addClass('fa-3x')
  , (e) ->
    $(e.target).removeClass('fa-3x')


- if @wiki_info.is_private && @wiki_info.controllable_by?(current_user)
  #private_members.modal.fade
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", "aria-hidden" => "true"} &times;
          %h3#private-members-label.text-center= t('terms.private_members')
        .modal-body
          %p
            - @wiki_info.visible_users.each do |user|
              - next if user == current_user
              %ul.list-unstyled.text-center
                %li
                  = "#{user.name} (#{user.email})"
                  = link_to raw('&times;'), remove_authority_user_path(wiki_name: @wiki_info.name, email: user.email), data: {method: :delete, confirm: t('actions.confirm_delete')}, style: 'color: #F00; font-weight: bold;'
        .modal-footer
          .text-center
            = form_tag add_authority_user_path(wiki_name: @wiki_info.name) do |f|
              = text_field_tag :email, nil, placeholder: 'Email', id: "add-user-input-field", class: 'typeahead tt-query'
              = submit_tag '+', class: 'btn btn-primary btn-xs'

    :coffeescript
      $ ->
        $('#add-user-input-field').typeahead
          name: 'Email'
          remote: "#{candidates_users_path(wiki_name: @wiki_info.name)}?q=%QUERY"
          limit: 10

%hr/

.text-center
  #page-items
    = render 'list_view_index'

:coffee
  $ ->
    $('#page-items').on 'ajax:success', '.reload-page-list,.switch-view', (data, res, xhr) ->
      $('#page-items').html(res)

app/views/pages/new.html.haml
= content_for :menu_link do
  = render 'menu_link'

= content_for :page_editable do
  .row
    %h2.text-center
      = "/#{@wiki_info.name}/"
      = text_field_tag :page, @page.url_name, placeholder: Page.human_attribute_name('url_name'), id: 'new-page-url-name', required: true
      %small= t('terms.page_url_name_pattern')
    %h3.text-center
      %small Page name
      = text_field_tag :page, @page.name, placeholder: t('terms.page_name_format_placeholder'), id: 'new-page-name', required: true
    = render 'form'


  :coffeescript
    $ ->
      get_markdown_text = ->
        $('#markdown-text').val()

      sending_page_body = (request_url, body) ->
        $.ajax
          type: 'POST'
          url: request_url
          data:
            previewed: true
            edited_user_id: "#{current_user.id}"
            body: body
          success: (data, textStatus, jqXHR) ->
            console.log data
            $('#preview-result').html data
          error: (data, textStatus, jqXHR) ->
            console.log textStatus

      render_preview = ->
        url = "#{preview_page_url(wiki_name: @wiki_info.name)}"
        sending_page_body(url, get_markdown_text)

      $('#markdown-text').keyup ->
        markdown_text = get_markdown_text()
        if (prev != markdown_text)
          prev = markdown_text
          render_preview()

      $('#new-page-name').keyup ->
        $('#page_name').val( $('#new-page-name').val())
      $('#new-page-url-name').keyup ->
        $('#page_url_name').val( $('#new-page-url-name').val())

app/views/pages/show.html.haml
= content_for :menu_link do
  = render 'menu_link'

= render 'shared/flash_messages'

.row
  .col-md-3
    %h4
      .label{class: ("label-#{@wiki_info.private_policy_label}")}
        - if @wiki_info.private?
          = fa_icon('lock')
        - else
          = fa_icon('unlock')

      = truncate(@wiki_info.name, length: 14)
    = link_to pages_path(wiki_name: @wiki_info.name) do
      = fa_icon('files-o')
      = t('terms.index_page')
    = fa_icon('reply')

  .col-md-7
    %h2
      .text-center
        - if @wiki_info.private?
          %small= fa_icon('lock')
        = truncate(@page.name, length: 20)
  .col-md-2
    .pull-right
      = link_to fa_icon('edit 2x'), edit_page_path(wiki_name: @wiki_info.name, page_name: @page.url_name), class: 'action-icons', id: 'edit-page-icon'
      - if @page.deletable_by?(current_user)
        = link_to fa_icon('trash-o 2x'), page_path(wiki_name: @wiki_info.name, page_name: @page.url_name), data: {confirm: t('actions.confirm_delete'), method: :delete}, class: 'action-icons', id: 'destory-page-icon'

:coffeescript
  $ ->
    $('.action-icons').hover (e) ->
      $(e.target).addClass('fa-3x')
    , (e) ->
      $(e.target).removeClass('fa-3x')

%hr
#page-content

:coffeescript
  $ ->
    request_url = "#{preview_page_url(wiki_name: @wiki_info.name, page_name: @page.url_name)}"
    PageContent.get(request_url, '#page-content')

%hr

%ul
  - unless @files.empty?
    %h5
      = fa_icon('files-o 2x')
      = t('terms.attachment_file')

  - @files.each do |file|
    %li
      = link_to file.attachment_file_name, attachment_path(wiki_name: @wiki_info.name, page_name: @page.url_name, id: file)
      = link_to fa_icon('trash-o'), attachment_path(wiki_name: @wiki_info.name, page_name: @page.url_name, id: file), data: {method: :delete, confirm: 'Are you sure?'}

= form_for @attachment, url: file_upload_path(wiki_name: @wiki_info.name, page_name: @page.url_name), html: { multipart: true, role: "form"} do |f|
  .form-group
    = f.file_field :attachment
  .form-group
    = f.submit 'File Upload', class: 'btn btn-primary btn-xs'

-# = link_to fa_icon('file-o')

%small.pull-right
  = "Last edited by "
  = image_tag(avatar_url(@wiki_info.creator, size: 20))
  = @page.last_editor_name
  = time_ago_in_words(@page.updated_at)

- if @page.histories.size > 1
  %h4= t('terms.page_history')
  - @page.histories.each do |h|
    %p= link_to "#{h[:date].to_s(:db)} (by #{h[:author]})", histories_page_path(wiki_name: @wiki_info.name, page_name: @page.url_name, sha: h[:sha])
  = link_to t('terms.histories_more'), histories_page_path(wiki_name: @wiki_info.name, page_name: @page.url_name), id: 'histories_more', class: 'btn btn-small btn-inverse'