config/routes.rb
Rails.application.routes.draw do

  root :to => "wiki_informations#index"

  get "search" => "search#index", :as => 'search'

  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy", :as => "logout"
  get "logout" => "sessions#destroy" # ログインできなくなる対策で
  get "oauth/callback" => "sessions#callback"
  get "oauth/:provider" => "sessions#oauth", :as => :auth_at_provider
  resources :password_resets, only: %i[new create edit update]

  get "/setting" => "users#setting", :as => 'user_setting'
  put "/setting/:id" => "users#update", :as => 'update_setting'
  get "/users/:token/activate" => "users#activate", :as => 'activate_user'
  put "/users/:token/register" => "users#register", :as => 'regist_user'

  namespace :admin do
    resources :users do
      member do
        get :candidates_wiki
        post :add_visibility_wiki
        delete :delete_visibility_wiki
        get :resend_invite_mail
        patch :unlock
      end
    end
  end
  post "/admin/users/invite" => 'admin/users#invite_user', :as => 'invite_user'

  resources :wiki_infos, :controller => 'wiki_informations', :only => [:index, :new, :create]
  get ':wiki_name/candidates_users' => 'wiki_informations#visible_wiki_candidates_users', :as => :candidates_users
  get ':wiki_name' => 'wiki_informations#show', :as => 'wiki'
  get ':wiki_name/edit' => 'wiki_informations#edit', :as => 'edit_wiki_info'
  put ':wiki_name' => 'wiki_informations#update', :as => 'update_wiki'
  post ':wiki_name/add_authority_user' => 'wiki_informations#add_authority_user', :as => 'add_authority_user'
  delete '/:wiki_name/remove_authority_user' => 'wiki_informations#remove_authority_user', :as => 'remove_authority_user'
  delete '/:wiki_name' => 'wiki_informations#destroy', :as => 'wiki_info'

  scope ':wiki_name' do
    resources :pages, only: [:index, :create, :new]
    get '/list_view_index' => 'pages#list_view_index', :as => 'list_view_pages'
    get '/globe_view_index' => 'pages#globe_view_index', :as => 'globe_view_pages'
    get '/markdown_help' => 'pages#help', :as => 'help'
    post '/preview' => 'pages#preview', :as => 'preview_page'
    get '/:page_name/histories' => 'pages#histories', :as => 'histories_page'
    put '/:page_name/histories/revert_page' => 'pages#revert', :as => 'revert_page'
    get '/:page_name' => 'pages#show', :as => 'page'
    get '/:page_name/edit' => 'pages#edit', :as => 'edit_page'
    put '/:page_name' => 'pages#update', :as => 'update_page'
    post '/:page_name/attachments' => 'pages#file_upload', :as => 'file_upload'
    get '/:page_name/attachments/:id' => 'pages#attachment', :as => 'attachment'
    delete '/:page_name/attachments/:id' => 'pages#file_destroy', :as => 'attachments'
    delete '/:page_name' => 'pages#destroy', :as => 'delete_page'
  end
end

app/models/wiki_information.rb
class WikiInformation < ActiveRecord::Base

  PermissionError = Class.new(StandardError)
  BASE_GIT_DIRECTORY = Rails.root.join(Settings.data_dir.wiki).freeze
  RESERVED_NAMES = %w(admin setting search).freeze

  has_many :pages, dependent: :destroy
  has_many :visibilities, dependent: :destroy
  has_many :visible_users, through: :visibilities, source: :user
  belongs_to :creator, class_name: 'User', foreign_key: 'created_by'
  belongs_to :updator, class_name: 'User', foreign_key: 'updated_by'

  validates :name, presence: true, uniqueness: true,
    format: { with: /\A[a-z0-9]([-a-z0-9]+)?\Z/i, message: :wrong_format_wiki_name},
    length: { maximum: 50 }, exclusion: { in: RESERVED_NAMES }

  before_save :set_visivilities
  before_create :prepare_git_repository
  before_update :rename_repository_directory
  after_create :setup_home_page
  after_destroy :cleanup_git_repository
  after_update :clear_private_memberships, if: Proc.new{|w| w.public? }

  scope :accessible_by, ->(user) do
    if user.guest?
      user.visible_wikis
    else
      WikiInformation.includes(:visibilities).where(
        "visibilities.user_id = ? OR wiki_informations.is_private = ?", user.id, false
      ).references(:visibilities)
    end
  end

  def private?
    is_private?
  end

  def public?
    not is_private?
  end

  def git_directory(overwrite_name = nil)
    BASE_GIT_DIRECTORY.join("#{overwrite_name or name}.git").to_s
  end

  def collaborator_for_private_wiki?(user)
    if user.guest?
      return visibilities.find_by(user_id: user.id).present?
    end
    return true if public?
    visibilities.find_by(user_id: user.id).present?
  end

  def welcome_page
    pages.where(url_name: 'welcome').first
  end

  def publish_by!(user)
    raise PermissionError if user.nil? || user.guest?
    update_attributes!(is_private: false, updated_by: user.id)
  end

  def hide_by!(user)
    raise PermissionError if user.nil? || user.guest?
    update_attributes!(is_private: true, updated_by: user.id)
  end

  private

  def rename_repository_directory
    return unless name_changed?
    FileUtils.rm_rf(git_directory) if File.exists? git_directory
    File.rename(git_directory(name_was), git_directory(name))
  end

  def prepare_git_repository
    FileUtils.rm_rf(git_directory) if File.exists? git_directory
    Grit::Repo.init(git_directory)
  end

  def set_visivilities
    return unless private?
    if new_record?
      visibilities.build(user_id: created_by)
    else
      visibilities.find_or_initialize_by(user_id: updated_by)
    end
  end

  def setup_home_page
    self.pages.create(url_name: 'welcome', name: 'Welcome', body: 'Getting started guide', updated_by: self.created_by)
  end

  def cleanup_git_repository
    FileUtils.rm_rf(self.git_directory)
  rescue => e
    logger.warn "Failed Cleanup Git Repository: #{e.message}"
  end

  # guest ユーザは閲覧性を保持し、それ以外のユーザには開放する
  def clear_private_memberships
    Visibility.where(wiki_information_id: self.id).includes(:user).
      where(users: {limited: false}).references(:users).destroy_all
  end

end

app/controllers/wiki_informations_controller.rb
class WikiInformationsController < ApplicationController

  before_filter :reject_limited_user, except: %i[index show]
  before_filter :find_wiki_info, only: %i[show edit update destroy add_authority_user remove_authority_user visible_wiki_candidates_users]

  def index
    @wiki_informations = WikiInformation.order(updated_at: :desc).accessible_by(current_user)
  end

  def show
    @page = @wiki_info.welcome_page
  end

  def new
    @wiki_info = WikiInformation.new
  end

  def edit
  end

  def create
    @wiki_info = WikiInformation.new(wiki_info_params.merge(created_by: current_user.id, updated_by: current_user.id))

    if @wiki_info.save
      redirect_to wiki_info_path(wiki_name: @wiki_info.name), notice: t('terms.created_wiki')
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @wiki_info.update_attributes(wiki_info_params.merge(updated_by: current_user.id))
        format.html { redirect_to edit_wiki_info_path(wiki_name: @wiki_info.name), notice: t('terms.updated_wiki')}
        format.json { head :no_content }
      else
        format.html { render :edit}
        format.json { render json: @wiki_information.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @wiki_info.destroy
    redirect_to root_path
  end

  def add_authority_user
    result = {success: '', failed: ''}
    user = User.active.where(email: params[:email]).first!
    @wiki_info.visible_users << user
    result[:success] = "Added #{user.name}"
  rescue => e
    logger.warn "Failed add user: #{e.message}"
    result[:failed] = "Failed add user: #{e.message}"
  ensure
    if request.xhr?
      render partial: 'private_members', layout: false
    else
      redirect_to edit_wiki_info_path(wiki_name: @wiki_info.name), notice: result[:success], error: result[:failed]
    end
  end

  def remove_authority_user
    result = {success: '', failed: ''}
    user = User.active.where(email: params[:email]).first!
    user.visibilities.find_by(wiki_information_id: @wiki_info.id).destroy!
    result[:success] = "Removed #{user.name}"
  rescue => e
    logger.warn "Failed remove user #{user.name}: #{e.message}"
    result[:failed] = "Failed remove user #{user.name}"
  ensure
    if request.xhr?
      render partial: 'private_members', layout: false
    else
      redirect_to edit_wiki_info_path(wiki_name: @wiki_info.name), notice: result[:success], error: result[:failed]
    end
  end

  def visible_wiki_candidates_users
    users = User.active.visible_wiki_candidates_on(@wiki_info)
    users = users.where("users.email LIKE :email OR users.name LIKE :name", email: "%#{params[:q]}%", name: "%#{params[:q]}%") if params[:q].present?
    email_list = users.map {|user| {value: user.email, tokens: [user.email, user.name] }}
    render json: email_list, layout: false
  end


  private

  def wiki_info_params
    params.require(:wiki_information).permit(:name, :is_private)
  end

  def find_wiki_info
    @wiki_info = WikiInformation.where(name: params[:wiki_name]).first!
  rescue => e
    logger.warn "Not found wiki: #{e.message}"
    unless request.xhr?
      redirect_to root_path, alert: t('terms.not_found_wiki_of', wiki: params[:wiki_name])
    end
  end

  def reject_limited_user
    if current_user.guest?
      redirect_to root_path and return
    end
    true
  end
end

app/views/wiki_informations/_form.html.haml
= error_messages_for(@wiki_info)

.form-group
  .col-sm-3.control-label= f.label :name
  .col-sm-5= f.text_field :name, :required => true, :placeholder => 'wiki name...', class: 'form-control'
.form-group
  .col-sm-3.control-label= f.label :is_private
  .col-sm-5= f.select :is_private, [[t('terms.publicity'), false], [t('terms.limited_publicity'), true]], {}, {class: 'form-control', 'ng-model'=>'privatePolicy', 'ng-init'=>"privatePolicy='#{@wiki_info.is_private?}'"}

app/views/wiki_informations/_menu_link.html.haml
- unless current_user.limited?
  .navbar-text= link_to t('terms.new_wiki'), new_wiki_info_path

app/views/wiki_informations/_private_members.html.haml
%hr
.text-center
  %h3= t('terms.private_members')

  - @wiki_info.visible_users.each do |user|
    - next if user == current_user
    %ul.list-unstyled
      %li
        %h4
          = "#{user.name} (#{user.email})"
          = link_to raw('&times;'), remove_authority_user_path(wiki_name: @wiki_info.name, email: user.email), remote: true, method: :delete, class: 'handling-private-member remove-private-member', style: 'color: #F00; font-weight: bold;'

  .text-center
    = form_tag add_authority_user_path(wiki_name: @wiki_info.name), remote: true, class: 'form-inline handling-private-member'  do
      = text_field_tag :email, nil, placeholder: 'Email', id: "add-user-input-field", class: 'typeahead tt-query'
      = submit_tag '+', class: 'btn btn-xs btn-primary'

:coffee
  $ ->
    $('.remove-private-member').click ->
      if confirm "#{t('actions.confirm_delete')}"
        $(this).parent().hide("highlight", 'slow')
      else
        return false

    $('body').on 'ajax:success', '.handling-private-member', (data, res, xhr) ->
      $('#private-members').html(res)

    $('#add-user-input-field').typeahead
      name: 'Email'
      remote: "#{candidates_users_path(wiki_name: @wiki_info.name)}?q=%QUERY"
      limit: 10

app/views/wiki_informations/_welcome_menu_link.html.haml
.navbar-text= link_to t('terms.wiki_home'), wiki_info_path(wiki_name: @wiki_info.name)
.navbar-text= link_to t('terms.new_page'), new_page_path(wiki_name: @wiki_info.name)

app/views/wiki_informations/edit.html.haml
= content_for :menu_link do
  = render 'menu_link'

= render 'shared/flash_messages'

.col-md-offset-2{'ng-controller' => 'wikiItemsController'}
  = form_for @wiki_info, url: wiki_info_path(wiki_name: @wiki_info.name) , html: {method: :put, class: 'form-horizontal', role: 'form'} do |f|

    = render 'form', f: f

    .form-group
      .col-sm-offset-3.col-sm-10
        = f.submit t('actions.update'), :class => 'btn btn-primary'
        = link_to t('actions.return_back'), root_path, :class => 'btn'

  #private-members{'ng-show' => "isShow"}
    = render 'private_members'

app/views/wiki_informations/index.html.haml
= content_for :menu_link do
  = render 'wiki_informations/menu_link'

%h1.text-center= t('terms.index_wiki')

= render 'shared/flash_messages'

%table.table.table-hover
  - @wiki_informations.each do |wiki|
    %tr.wiki-items
      %td{class: "#{wiki.private? ? 'warning' : ''}", 'ng-controller' => 'wikiItemsController', 'ng-mouseover' => "showActionBtn()", 'ng-mouseleave' => "hideActionBtn()"}
        .col-md-2
          %h4
            .label{class: "label label-#{wiki.private_policy_label}"}
              - if wiki.private?
                = fa_icon('lock')
              = wiki.private_policy

        .col-md-8
          %h3
            = link_to wiki.name, wiki_info_path(wiki_name: wiki.name)
            %small.pull-right= l wiki.updated_at

        - unless current_user.limited?
          .col-md-2.actions{'ng-show' => "isShow"}
            %h4
              = link_to fa_icon('edit 2x'), edit_wiki_info_path(wiki_name: wiki.name)
              = link_to fa_icon('trash-o 2x'), wiki_info_path(wiki_name: wiki.name), data: {method: :delete, confirm: t('actions.confirm_delete')}

app/views/wiki_informations/new.html.haml
= content_for :menu_link do
  = render 'menu_link'

%h1.text-center= t('actions.new_wiki')

.col-md-offset-2
  = form_for @wiki_info, url: wiki_infos_path, html: {method: :post, class: 'form-horizontal', role: 'form'} do |f|

    = render 'form', f: f

    .form-group
      .col-sm-offset-3.col-sm-10
        = f.submit t('actions.save'), class: 'btn btn-primary'
        = link_to t('actions.return_back'), root_path, :class => 'btn'

app/views/wiki_informations/show.html.haml
= content_for :menu_link do
  = render 'welcome_menu_link'

= render 'shared/flash_messages'

.row
  .col-md-3
    %h4
      .label{class: ("label-#{@wiki_info.private_policy_label}")}
        - if @wiki_info.private?
          = fa_icon('lock')
        - else
          = fa_icon('unlock')

      = truncate(@wiki_info.name, length: 14)
    = link_to pages_path(wiki_name: @wiki_info.name) do
      = fa_icon('files-o')
      = t('terms.index_page')
    = fa_icon('reply')

  .col-md-7
    %h2
      .text-center
        - if @wiki_info.private?
          %small= fa_icon('lock')
        = truncate(@page.name, length: 20)
  .col-md-2
    .pull-right
      = link_to fa_icon('edit 2x'), edit_page_path(wiki_name: @wiki_info.name, page_name: @page.url_name), class: 'action-icons'

:coffeescript
  $ ->
    $('.action-icons').hover (e) ->
      $(e.target).addClass('fa-3x')
    , (e) ->
      $(e.target).removeClass('fa-3x')

%hr
#page-content

:coffeescript
  $ ->
    request_url = "#{preview_page_url(wiki_name: @wiki_info.name, page_name: @page.url_name)}"
    $.ajax
      type: 'POST'
      url: request_url
      success: (data, textStatus, jqXHR) ->
        # console.log data
        $('#page-content').html data
      error: (data, textStatus, jqXHR) ->
        console.log textStatus

%hr

%small.pull-right
  = "Last edited by "
  = image_tag(avatar_url(@wiki_info.creator, size: 20))
  = @page.last_editor_name
  = time_ago_in_words(@page.updated_at)

- if @page.histories.size > 1
  %h4= t('terms.page_history')
  - @page.histories.each do |h|
    %p= link_to "#{h[:date].to_s(:db)} (by #{h[:author]})", histories_page_path(wiki_name: @wiki_info.name, page_name: @page.url_name, sha: h[:sha])
  = link_to t('terms.histories_more'), histories_page_path(wiki_name: @wiki_info.name, page_name: @page.url_name), id: 'histories_more', class: 'btn btn-small btn-inverse'