config/routes.rb
Rails.application.routes.draw do

  root :to => "wiki_informations#index"

  get "search" => "search#index", :as => 'search'

  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy", :as => "logout"
  get "logout" => "sessions#destroy" # ログインできなくなる対策で
  get "oauth/callback" => "sessions#callback"
  get "oauth/:provider" => "sessions#oauth", :as => :auth_at_provider
  resources :password_resets, only: %i[new create edit update]

  get "/setting" => "users#setting", :as => 'user_setting'
  put "/setting/:id" => "users#update", :as => 'update_setting'
  get "/users/:token/activate" => "users#activate", :as => 'activate_user'
  put "/users/:token/register" => "users#register", :as => 'regist_user'

  namespace :admin do
    resources :users do
      member do
        get :candidates_wiki
        post :add_visibility_wiki
        delete :delete_visibility_wiki
        get :resend_invite_mail
        patch :unlock
      end
    end
  end
  post "/admin/users/invite" => 'admin/users#invite_user', :as => 'invite_user'

  resources :wiki_infos, :controller => 'wiki_informations', :only => [:index, :new, :create]
  get ':wiki_name/candidates_users' => 'wiki_informations#visible_wiki_candidates_users', :as => :candidates_users
  get ':wiki_name' => 'wiki_informations#show', :as => 'wiki'
  get ':wiki_name/edit' => 'wiki_informations#edit', :as => 'edit_wiki_info'
  put ':wiki_name' => 'wiki_informations#update', :as => 'update_wiki'
  post ':wiki_name/add_authority_user' => 'wiki_informations#add_authority_user', :as => 'add_authority_user'
  delete '/:wiki_name/remove_authority_user' => 'wiki_informations#remove_authority_user', :as => 'remove_authority_user'
  delete '/:wiki_name' => 'wiki_informations#destroy', :as => 'wiki_info'

  scope ':wiki_name' do
    resources :pages, only: [:index, :create, :new]
    get '/list_view_index' => 'pages#list_view_index', :as => 'list_view_pages'
    get '/globe_view_index' => 'pages#globe_view_index', :as => 'globe_view_pages'
    get '/markdown_help' => 'pages#help', :as => 'help'
    post '/preview' => 'pages#preview', :as => 'preview_page'
    get '/:page_name/histories' => 'pages#histories', :as => 'histories_page'
    put '/:page_name/histories/revert_page' => 'pages#revert', :as => 'revert_page'
    get '/:page_name' => 'pages#show', :as => 'page'
    get '/:page_name/edit' => 'pages#edit', :as => 'edit_page'
    put '/:page_name' => 'pages#update', :as => 'update_page'
    post '/:page_name/attachments' => 'pages#file_upload', :as => 'file_upload'
    get '/:page_name/attachments/:id' => 'pages#attachment', :as => 'attachment'
    delete '/:page_name/attachments/:id' => 'pages#file_destroy', :as => 'attachments'
    delete '/:page_name' => 'pages#destroy', :as => 'delete_page'
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  never_wastes

  attr_accessor :password, :password_confirmation, :on_reset_password

  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :visibilities, dependent: :destroy
  has_many :visible_wikis, through: :visibilities, source: :wiki_information
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  scope :visible_wiki_candidates_on, ->(wiki) do
    where.not(id: wiki.visible_users.pluck("users.id"))
  end
  scope :not_admin, ->{ where(admin: false) }
  scope :active, ->{ where(activation_state: 'active') }
  scope :pending, ->{ where(activation_state: 'pending') }
  scope :locked, ->{ unscoped.where(deleted: true) }

  validates_presence_of :name, on: :update
  validates :email, presence: true, uniqueness: true
  validates_inclusion_of :role, in: %w(admin member guest), message: :invalid_user_role
  validates_inclusion_of :admin, in: lambda{|u| u.admin_validetes_include_values}, message: :invalid_admin_select
  validates_inclusion_of :limited, in: lambda{|u| u.limited__validetes_include_values}, message: :invalid_limited_select
  validate :password_check

  def activated?
    activation_state == "active"
  end

  def pending?
    activation_state == "pending"
  end

  def guest?
    limited?
  end

  def unlock!
    self.deleted = false
    self.deleted_at = nil
    self.save!
  end

  def lock_or_destroy_by(operator)
    return "failed" if self == operator
    if pending? or deleted?
      self.demolish
      message = I18n.t('terms.deleted_user_info')
    else
      self.destroy
      message = I18n.t('terms.locked_user_info')
    end
    message
  end

  def self.role_list
    [%w(管理者 admin), %w(メンバー member), %w(ゲスト guest)]
  end

  def role
    if admin?
      'admin'
    elsif guest?
      'guest'
    else
      'member'
    end
  end

  def role=(role)
    case role
    when 'admin'
      self.admin = true
      self.limited = false
    when 'guest'
      self.limited = true
      self.admin = false
    else
      self.admin = false
      self.limited = false
    end
  end

  def activation_expired?
    return false if activated?
    pending? and activation_token_expires_at.try(:past?)
  end

  def unvisible_wikis
    WikiInformation.all - visible_wikis
  end

  def admin_validetes_include_values
    limited? ? [false] : [true, false]
  end

  def limited__validetes_include_values
    admin? ? [false] : [true, false]
  end

  def reset_activation!
    self.setup_activation
    self.save!(validate: false)
  end


  private

  def password_check
    if activated? && (not on_reset_password)
      return true if password.blank? && password_confirmation.blank?
    else # for activation
      unless password.present? && password_confirmation.present?
        errors.add :base, :blank_password
        return false
      end
    end
    errors.add :base, :unmatched_password unless password == password_confirmation
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :require_admin_user
  before_filter :find_user, only: %i(show edit update destroy add_visibility_wiki delete_visibility_wiki candidates_wiki resend_invite_mail unlock)

  def index
    @active_users = User.active
    @invalidity_users = User.pending
    @locked_users = User.locked
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user), notice: t('terms.updated_user_info')
    else
      render :edit
    end
  end

  def destroy
    result_message = @user.lock_or_destroy_by(current_user)
    redirect_to admin_users_path, notice: result_message
  end

  def unlock
    @user.unlock!
    redirect_to admin_users_path, notice: t('terms.unlocked_user_info')
  end

  def add_visibility_wiki
    wiki = WikiInformation.find_by(name: params[:wiki_name])
    @user.visible_wikis << wiki
    @user.reload
    redirect_to admin_user_path(@user), notice: t('terms.candidates_wiki_of', wiki: wiki.name)
  end

  def delete_visibility_wiki
    wiki = WikiInformation.find_by(id: params[:wiki_id])
    @user.visible_wikis.delete(wiki)
    @user.reload
    redirect_to admin_user_path(@user), notice: t('terms.unvisible_wiki_of', wiki: wiki.name)
  end

  def candidates_wiki
    unvisible_wiki_list = @user.unvisible_wikis
    wikiname_list = unvisible_wiki_list.map {|wiki| {value: wiki.name, tokens: [wiki.name] }}
    render json: wikiname_list, layout: false
  end

  def invite_user
    user = build_invite_user
    if user.valid? and user.save(validate: false)
      redirect_to admin_users_path, notice: t('terms.sent_invite_mail_of', email: user.email)
    else
      redirect_to admin_users_path, alert: t('terms.vailed_invite_mail_of', email: user.email)
    end
  end

  def resend_invite_mail
    @user.reset_activation!
    UserMailer.activation_needed_email(@user).deliver
    redirect_to admin_users_path, notice: t('terms.resent_invite_mail_of', email: @user.email)
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end

  def find_user
    user_scope = User.all
    user_scope = user_scope.with_deleted if %w(unlock destroy).include?(params[:action])
    @user = user_scope.find_by!(id: params[:id])
  end

  def require_admin_user
    redirect_to root_path unless current_user.admin?
  end

  def build_invite_user
    User.new(user_params.merge(name: '', password: 'sample', password_confirmation: 'sample'))
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout 'login', only: [:register, :activate]

  skip_before_filter :require_login, only: [:register, :activate]

  def setting
    @user = current_user
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_setting_path, notice: t('terms.updated_user_info')
    else
      render :setting
    end
  end

  def activate
    unless @user = User.load_from_activation_token(params[:token])
      flash[:error] = t('terms.invalid_activation_token')
      redirect_to login_path
    end
  end

  def register
    @user = User.load_from_activation_token(params[:token])
    if @user.update_attributes(user_params)
      @user.activate!
      auto_login(@user)
      redirect_to root_path, notice: t('terms.registered_user_info')
    else
      render :activate
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :remember_me_token)
  end
end

app/views/admin/users/_form.html.haml
- newly = @user.new_record?
- form_url = newly ? admin_users_path : admin_user_path(@user)
- http_method = newly ? :post : :put
= form_for(@user, :url => form_url, :html => {:method => http_method, :class => "form-horizontal", role: 'form'}) do |f|

  = error_messages_for(@user)

  .form-group
    .col-sm-3.control-label= f.label :name, :class => "control-label"
    .col-sm-5= f.text_field :name, :placeholder => User.human_attribute_name(:name), class: 'form-control'

  .form-group
    .col-sm-3.control-label= f.label :email, :class => "control-label"
    .col-sm-5= f.text_field :email, :placeholder => User.human_attribute_name(:email), class: 'form-control'

  .form-group
    .col-sm-3.control-label= f.label :password, :class => "control-label"
    .col-sm-5= f.password_field :password, :placeholder => User.human_attribute_name(:password), class: 'form-control'

  .form-group
    .col-sm-3.control-label= f.label :password_confirmation, :class => "control-label"
    .col-sm-5= f.password_field :password_confirmation, :placeholder => User.human_attribute_name(:password_confirmation), class: 'form-control'

  .form-group
    .col-sm-3.control-label= f.label :role, :class => "control-label"
    .col-sm-5= f.select :role, options_for_select(User.role_list, @user.role), {}, class: 'form-control'

  .form-group
    .col-sm-offset-3.col-sm-10
      = f.submit (newly ? t('actions.add_user') : t('actions.update')), :class => 'btn btn-primary'
      = link_to t('actions.show_detail'), admin_user_path(@user), :class => 'btn'

app/views/admin/users/_visible_wiki.html.haml
- if @user.limited
  %h2.text-center
    = fa_icon('book')
    Wiki

  - @user.visible_wikis.each do |wiki|
    .col-xs-offset-3.col-xs-10
      %h3
        = wiki.name
        = link_to delete_visibility_wiki_admin_user_path(@user, wiki_id: wiki.id), method: :delete do
          = fa_icon('trash-o')

  .text-center
    = form_tag add_visibility_wiki_admin_user_path(@user), class: 'form-inline'  do
      = text_field_tag :wiki_name, nil, placeholder: 'Wiki name...', id: "add-wiki-input-field", class: 'typeahead tt-query'
      = submit_tag '+', class: 'btn btn-primary'

:coffee
  $ ->
    $('#add-wiki-input-field').typeahead
      name: 'Wiki name'
      remote: "#{candidates_wiki_admin_user_path(@user)}"
      limit: 10

app/views/admin/users/edit.html.haml
%h1.col-sm-offset-3= t('actions.editing_of', :target => User.model_name.human)

= render 'form'

app/views/admin/users/index.html.haml
%h2.text-center
  = fa_icon('users')
  = t('terms.admin_user_index')

= render 'shared/flash_messages'

%table.table.table-hover
  - @active_users.each do |user|
    %tr.users{class: "#{user == current_user ? 'active' : ''}"}
      %td{'ng-controller' => 'usersController', 'ng-mouseover' => "showActionBtn()", 'ng-mouseleave' => "hideActionBtn()" }
        .row
          .col-md-1.col-xs-offset-1
            %h5
              = user.formatted_kind
          .col-md-1
            = image_tag avatar_url(user, size: 30)
          .col-md-6
            = link_to admin_user_path(user) do
              %h4
                - if user == current_user
                  myself
                - else
                  %strong= user.name
                  %small= " ( #{user.email} )"
          - unless current_user == user
            .col-md-3.actions{'ng-show' => "isShow"}
              .pull-right
                = link_to fa_icon('edit 2x'), edit_admin_user_path(user), class: 'edit_user_button'
                = link_to fa_icon('lock 2x'), admin_user_path(user), data: {method: :delete, confirm: t('actions.confirm_lock')}, class: 'lock_user_button'

%hr
- unless @invalidity_users.empty?

  .text-center
    %h3
      = fa_icon('rocket')
      = t('terms.index_inviting_user')
      %small= link_to fa_icon('question'), "#", rel: 'tooltip', :"data-placement" => "top", title: t('terms.activation_token_expiration_period')

  %table.table.table-hover
    - @invalidity_users.each do |user|
      %tr{class: "#{user.activation_expired? ? 'danger' : 'users'}"}
        %td
          .col-md-2.col-md-offset-2.text-right= user.formatted_kind
          .col-md-5
            = user.email
            = link_to admin_user_path(user), style: 'color: red;', data: {method: :delete, confirm: t('actions.confirm_delete')} do
              = fa_icon('times-circle')
          .col-md-3.actions{class: "#{user.activation_expired? ? '' : 'hide'}"}
            = link_to resend_invite_mail_admin_user_path(user) do
              = fa_icon('mail-forward')
              = fa_icon('envelope-o')
            - if user.activation_expired?
              .pull-right= link_to fa_icon('question'), "#", rel: 'tooltip', :"data-placement" => "top", title: t('terms.hint_token_expired_user')

- unless @locked_users.empty?
  .text-center
    %h4
      = fa_icon('lock')
      = t('terms.index_locked_user')

  %table.table.table-hover
    - @locked_users.each do |user|
      %tr
        %td
          .col-md-2.col-md-offset-2.text-right= user.formatted_kind
          .col-md-5
            = "#{user.name} (#{user.email})"
            = link_to unlock_admin_user_path(user), data: {method: :patch, confirm: t('actions.confirm_unlock')}, class: 'unlock-user-button' do
              = fa_icon('unlock')
            = link_to admin_user_path(user), style: 'color: red;', data: {method: :delete, confirm: t('actions.confirm_delete')}, class: 'destroy-user-button' do
              = fa_icon('times-circle')

.text-center= link_to t('actions.invite_user'), '#invite-user-form', class: 'btn btn-primary', data: {toggle: "modal"}

#invite-user-form.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", "aria-hidden" => "true"} &times;
        %h3#invite-user-label.text-center= t('actions.invite_user')
      .modal-body
        %p
          = form_for User.new, url: invite_user_path, html: {class: 'form-horizontal', role: 'form'} do |f|
            .form-group
              .col-sm-4.control-label= f.label :email
              .col-sm-6= f.email_field :email, placeholder: User.human_attribute_name(:email), class: 'form-control'

            .form-group
              .col-sm-4.control-label= f.label :role, :class => "control-label"
              .col-sm-6= f.select :role, options_for_select(User.role_list), {}, class: 'form-control'

            .form-group.actions
              .col-sm-offset-4.col-sm-6
                = f.submit t('actions.invite'), class: 'btn btn-primary', id: 'invite_user_button'
                %button{"data-dismiss" => "modal", "aria-hidden" => "true", class: 'btn'}= t('actions.cancel')
      .modal-footer

:coffeescript
  $ ->
    $('#invite_user_button').on 'click', (ev) ->
      location.reload

app/views/admin/users/new.html.haml
%h1.col-sm-offset-3= t('actions.add_user')

= render 'form'

app/views/admin/users/show.html.haml
%h4
  .pull-left
    = link_to t('terms.index_user'), admin_users_path
    = fa_icon('hand-o-left')
  .pull-right
    = link_to fa_icon('edit 2x'), edit_admin_user_path(@user), class: 'edit_user_button'
    - unless @user == current_user
      = link_to fa_icon('lock 2x'), admin_user_path(@user), data: {:method => :delete, :confirm => t('actions.confirm_delete')}, class: 'lock_user_button'


%h2.text-center
  %small= @user.formatted_kind
  = image_tag avatar_url(@user, size: 50)
  = @user.name.truncate(15)
  %br/
  %small= @user.email

= render 'shared/flash_messages'

%hr

= render 'visible_wiki'