config/routes.rb
Rails.application.routes.draw do

  root :to => "wiki_informations#index"

  get "search" => "search#index", :as => 'search'

  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy", :as => "logout"
  get "logout" => "sessions#destroy" # ログインできなくなる対策で
  get "oauth/callback" => "sessions#callback"
  get "oauth/:provider" => "sessions#oauth", :as => :auth_at_provider
  resources :password_resets, only: %i[new create edit update]

  get "/setting" => "users#setting", :as => 'user_setting'
  put "/setting/:id" => "users#update", :as => 'update_setting'
  get "/users/:token/activate" => "users#activate", :as => 'activate_user'
  put "/users/:token/register" => "users#register", :as => 'regist_user'

  namespace :admin do
    resources :users do
      member do
        get :candidates_wiki
        post :add_visibility_wiki
        delete :delete_visibility_wiki
        get :resend_invite_mail
        patch :unlock
      end
    end
  end
  post "/admin/users/invite" => 'admin/users#invite_user', :as => 'invite_user'

  resources :wiki_infos, :controller => 'wiki_informations', :only => [:index, :new, :create]
  get ':wiki_name/candidates_users' => 'wiki_informations#visible_wiki_candidates_users', :as => :candidates_users
  get ':wiki_name' => 'wiki_informations#show', :as => 'wiki'
  get ':wiki_name/edit' => 'wiki_informations#edit', :as => 'edit_wiki_info'
  put ':wiki_name' => 'wiki_informations#update', :as => 'update_wiki'
  post ':wiki_name/add_authority_user' => 'wiki_informations#add_authority_user', :as => 'add_authority_user'
  delete '/:wiki_name/remove_authority_user' => 'wiki_informations#remove_authority_user', :as => 'remove_authority_user'
  delete '/:wiki_name' => 'wiki_informations#destroy', :as => 'wiki_info'

  scope ':wiki_name' do
    resources :pages, only: [:index, :create, :new]
    get '/list_view_index' => 'pages#list_view_index', :as => 'list_view_pages'
    get '/globe_view_index' => 'pages#globe_view_index', :as => 'globe_view_pages'
    get '/markdown_help' => 'pages#help', :as => 'help'
    post '/preview' => 'pages#preview', :as => 'preview_page'
    get '/:page_name/histories' => 'pages#histories', :as => 'histories_page'
    put '/:page_name/histories/revert_page' => 'pages#revert', :as => 'revert_page'
    get '/:page_name' => 'pages#show', :as => 'page'
    get '/:page_name/edit' => 'pages#edit', :as => 'edit_page'
    put '/:page_name' => 'pages#update', :as => 'update_page'
    post '/:page_name/attachments' => 'pages#file_upload', :as => 'file_upload'
    get '/:page_name/attachments/:id' => 'pages#attachment', :as => 'attachment'
    delete '/:page_name/attachments/:id' => 'pages#file_destroy', :as => 'attachments'
    delete '/:page_name' => 'pages#destroy', :as => 'delete_page'
  end
end

app/views/layouts/application.html.haml
!!!
%html{lang: 'en', 'ng-app' => 'internalWiki'}
  %head
    = render 'shared/layout/head'
  %body
    %nav.navbar.navbar-default{role: 'navigation'}
      .navbar-brand
        = link_to root_path do
          = fa_icon('leaf')
          InternalWiki

      - if content_for?(:menu_link)
        = yield(:menu_link)

      = form_tag('#', class: 'navbar-form navbar-left', role: 'search', id: 'search-word-form', method: :get) do
        .form-group
          = text_field_tag :q, @search_word, placeholder: 'Search word...', class: 'form-control', id: 'search-query'
        = submit_tag t('terms.search'), class: 'btn btn-primary'
      - if current_user
        %ul.nav.navbar-nav.navbar-right
          %li.navbar-text= current_user.name
          %li
            %a{class: 'dropdown-toggle', :"data-toggle" => "dropdown", href: "#"}
              = image_tag avatar_url(current_user, size: 25)
              %b{class: "caret"}
            %ul{class: 'dropdown-menu'}
              %li= link_to t('terms.setting'), user_setting_path
              %li= link_to t('terms.logout'), logout_path
              - if current_user.admin?
                %li= link_to t('terms.user_control'), admin_users_path

    .container
      .row
        .col-md-12
          - if content_for?(:page_editable)
            = yield(:page_editable)
          - else
            .row
              .col-md-9
                = yield
              .col-md-3
                - if content_for?(:right_area)
                  = yield(:right_area)
                - else
                  .well.sidebar-nav
                    %h5= t('terms.recent_update_pages')
                    %ul.nav.nav-list
                      - Page.accessible_by(current_user).recently.each do |page|
                        %li
                          %small= link_to truncate(page.name, length: 13), page_path(wiki_name: page.wiki_name, page_name: page.url_name), rel: 'tooltip', :"data-placement" => "right", title: "Updated: #{l page.updated_at}"

:coffeescript
  $('#search-word-form').on 'submit', ->
    this.action = "/search?q=" + $('#search-word-form #search-query').val()
    this.submit()

app/views/layouts/login.html.haml
!!!
%html{:lang => "en"}
  %head
    = render 'shared/layout/head'
    :css
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 450px;
        padding: 19px 19px 29px 50px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="email"],
      .form-signin input[type="password"] {
        font-size: 20px;
        width: 350px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

  %body
    .container
      = yield